### ISSUE TITLE
Usage via NPM doesn't work

### ISSUE THREAD

**Issue by laurilarjo** [ToeFungi/exchange-rates-as-promised#2] opened 2019-12-30 09:56 UTC
Hi, I was searching for an exchange rate library, found yours and tried it out. But it seems this library is not meant to be used via NPM. My project is in typescript, but when I try to `import  { ExchangeRate, Currencies, ExchangeResponse } from 'exchange-rates-as-promised';` it doesn't find the module. Also your readme was written like it was meant to be used not from node_modules, but directly by using the source folder.

I haven't done NPM modules, so I'm not sure what you would need to do to make it work, but here's what I did to make it work:

1. I ran `npm add exchange-rates-as-promised`, and installed the package in the node_modules.
2. I went to folder `node_modules/exchange-rates-as-promised` and ran `npm install` and `npm run build` to build the index.js file into `build` directory.
3. I edited your package.json and changed `main` to point to `build/index.js`.

After those operations the module was found, and typing support was enabled also in VSCode, and I was able to use your package :)

I hope you can update this and make it easier to use. It's a very handy package!

**Comment by ToeFungi** [comment] 2020-01-07 12:13
@laurilarjo Hi,

Thanks for the feedback. Will take a look soon and see what I can do. I'm glad you managed to get the package to work in the end though and that you found it handy :+1:

**Comment by ToeFungi** [comment] 2020-01-07 12:58
@laurilarjo I see what the problem is. Will try get a fix out within a few working days

**Comment by ToeFungi** [comment] 2020-01-08 17:51
@laurilarjo It should be fixed now, try install v1.0.3 and see if the type definitions pull through properly.

**Comment by ShaunEgan** [comment] 2020-01-09 09:37
They work as expected for me on the current version.

**Comment by laurilarjo** [comment] 2020-01-11 13:34
@ToeFungi Hi, yes it works correctly now. Thanks a lot!

**Closed** 2020-01-11 13:34 UTC
Labels: fixed
